debug : false

# キー入力先になるウィンドウのタイトルの頭から数文字
# Title of the window that will receive keystrokes.
WindowName : Core Keeper

# 範囲外の場合、その音階に一番近い登録済みの音をコピーするかどうか
# If out of range, whether to copy the nearest note to that scale
OutOfRangeCopyNearestNote : true

# keyMapの値として当該キーを表す文字の代わりに仮想キーコードを使用するかどうか
forceUsingVKCode : false

# 高精度モード
# 実行間隔の単位をミリ秒からマイクロ秒に変更
HighPrecisionMode : false

# keymapに対して定義する (廃止予定)
NoteMinNumber : 65
NoteMaxNumber : 91

# 設定音階をズラす (加算、負の値も許容)
# keyMapを触らずにあとから調整するためのもの
NoteNumberOffset : 15